### ISSUE TITLE
Incompatible with SuaveIO >=v2.2.0 

### ISSUE THREAD

**Issue by Badmoonz** [ncthbrt/Fable.Websockets#1]
Hi!
Since v2.2.0  module YoLo was renamed to Suave.Utils.YoLo and became internal.
Can I pull request to your repo to update nuget package then?

Have caught problems with at runtime with :
  UTF8.toString
  UTF8.tobytes

**Comment by ncthbrt** [comment]
Sure. 😄 
Haven't been using Fable for a fair while as my new company is not a .NET house. 
But would be happy to review the code. And/or even give you commit access.

**Comment by ncthbrt** [comment]
@Badmoonz 
This repo also might be of help (has a sample of lib usage):
https://github.com/ncthbrt/Fable.Websockets.Elmish

**Comment by ncthbrt** [comment]
Oh you've already starred it haha.

**Comment by Badmoonz** [comment]
Can you tag versions?

**Comment by ncthbrt** [comment]
Didn't get around to auto releasing with travis 😞 
Do you have a nuget account?
Could add you as maintainer.

**Comment by Badmoonz** [comment]
Just registered at nuget
Same name @Badmoonz

**Comment by ncthbrt** [comment]
Cool. Says you need to verify your email before I can add you.

**Comment by Badmoonz** [comment]
done :)

**Comment by ncthbrt** [comment]
You're now the proud owner of a 3 nuget packages :P

**Comment by Badmoonz** [comment]
thx! gonna to add some docs and maybe test soon :D
